name: seach Image

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: search Docker Image
      run: docker search "${{ github.event.inputs.docker_image }}"

    - name: pull Docker Image
      run: docker pull "${{ github.event.inputs.docker_image }}"
           docker save "${{ github.event.inputs.docker_image }}" -o "output-arm64.tar"

    - name: Compress the TAR files
      run: tar -czf arm64-images.tar.gz output-arm64.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: arm64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm output-arm64.tar
